# Generated by Django 5.1.2 on 2024-10-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritemovie',
            name='movie_id',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='favoritemovie',
            unique_together={('person', 'movie_id')},
        ),
    ]
